---
- name: use our apt sources
  sudo: yes
  copy: src=files/apt-sources.list dest=/etc/apt/sources.list mode=0644 backup=yes

- name: update apt sources
  sudo: yes
  apt: update_cache=yes

- name: install essential software via apt
  sudo: true
  apt: name={{ item.package }}
  with_items:
    - package: build-essential
    - package: gawk
    - package: bison
    - package: autoconf
    - package: automake
    - package: git
    - package: git-doc
    - package: git-flow
    - package: nginx
    - package: nginx-extras
    - package: nginx-doc
    - package: python-psycopg2
    - package: postgresql
    - package: postgresql-client
    - package: libpq-dev
    - package: sqlite3
    - package: libsqlite3-dev
    - package: libyaml-dev
    - package: libgdbm-dev
    - package: libreadline-dev
    - package: libncurses5-dev
    - package: libxml2-dev
    - package: libxslt-dev
    - package: imagemagick
    - package: libmagickwand-dev
    - package: libmagickcore-dev
    - package: xvfb
    - package: redis-server
    - package: redis-tools
