---
- name: cloning node.js
  git: repo=https://github.com/joyent/node.git dest=node.js

- name: configure node.js
  command: ./configure chdir=node.js

- name: make node.js
  command: make chdir=node.js

- name: install node.js
  sudo: true
  command: make install chdir=node.js

