---
- name: clone ruby-install
  git: repo=https://github.com/postmodern/ruby-install.git dest=ruby-install update=yes

- name: install ruby-install
  sudo: true
  command: make install chdir=ruby-install creates=/usr/local/bin/ruby-install

- name: install ruby 2.2.0
  sudo: true
  command: /usr/local/bin/ruby-install ruby 2.2.0 creates=/opt/rubies/ruby-2.2.0

- name: clone chruby
  git: repo=https://github.com/postmodern/chruby.git dest=chruby update=yes

- name: install chruby
  sudo: true
  command: make install chdir=chruby creates=/usr/local/share/chruby

- name: install /etc/profile.d/chruby.sh
  sudo: true
  copy: src=files/chruby.sh dest=/etc/profile.d/chruby.sh owner=root group=root mode=0644

